language:
- python
python:
  - "2.7"
# whitelist of git branches to build
branches:
  only:
    - travis
# install some archive programs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev qt4-dev-tools
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: make test PYTESTOPTS="--tb=short"
# do not send emails of broken builds
notifications:
  email: false
